name: Go Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  go_tests_latest:
    runs-on: windows-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Run vet
        run: go vet ./...

      - name: Test
        run: go test --mode=unit -v ./...
  # go_tests_mac_latest:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Install Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: 1.24

  #     - name: Check out code into the Go module directory
  #       uses: actions/checkout@v4

  #     - name: Run vet
  #       run: go vet ./...

  #     - name: Test
  #       run: go test --mode=unit -v ./...
  go_tests_linux_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Run vet
        run: go vet ./...

      - name: Test
        run: go test --mode=unit -v ./...
  go_tests:
    runs-on: windows-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Run vet
        run: go vet ./...

      - name: Test
        run: go test --mode=unit -v ./...
  go_tests_mac:
    # TODO: Change to macos-latest once hanging issue is resolved.
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Run vet
        run: go vet ./...

      - name: Test
        run: go test --mode=unit -v ./...
  go_tests_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Run vet
        run: go vet ./...

      - name: Test
        run: go test --mode=unit -v ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --max-same-issues 0 --out-format colored-line-number --exclude-dirs=examples
